name: Actualización diaria panel de incendios

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: Europe/Madrid
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (if requirements.txt exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - name: Run script
        run: |
          python -V
          python PANEL_INCENDIOS.py
