name: Actualización diaria panel de incendios

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: Europe/Madrid
      GEOPANDAS_IO_ENGINE: pyogrio
      GOOGLE_CRED_PATH: /Users/miguel.ros/Desktop/GITHUB/repositorio_panel_incendios/credenciales_google_sheet.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyogrio==0.9.0

      - name: Create expected absolute paths and symlinks
        run: |
          sudo mkdir -p /Users/miguel.ros/Desktop/GITHUB
          sudo rm -rf /Users/miguel.ros/Desktop/GITHUB/repositorio_panel_incendios
          sudo ln -s "${GITHUB_WORKSPACE}" "/Users/miguel.ros/Desktop/GITHUB/repositorio_panel_incendios"

          sudo mkdir -p /Users/miguel.ros/Desktop
          sudo rm -rf /Users/miguel.ros/Desktop/PANEL_INCENDIOS
          sudo ln -s "${GITHUB_WORKSPACE}" "/Users/miguel.ros/Desktop/PANEL_INCENDIOS"

          sudo mkdir -p /Users/miguel.ros/GITHUB
          sudo rm -rf /Users/miguel.ros/GITHUB/repositorio_panel_incendios
          sudo ln -s "${GITHUB_WORKSPACE}" "/Users/miguel.ros/GITHUB/repositorio_panel_incendios"

      - name: Write Google credentials from secret (with correct ownership)
        shell: bash
        run: |
          dir="$(dirname "$GOOGLE_CRED_PATH")"
          sudo mkdir -p "$dir"

          # Escribir el JSON como root (por la ruta bajo /Users/...), luego reasignar propietario al usuario runner
          sudo bash -lc "cat > '$GOOGLE_CRED_PATH' << 'JSON'
          ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_JSON }}
          JSON"

          # Asegurar propiedad y permisos para que Python pueda leerlo
          sudo chown -R "$USER":"$USER" "$dir"
          chmod 600 "$GOOGLE_CRED_PATH"

          echo "Credenciales escritas en $GOOGLE_CRED_PATH con propietario $USER y modo 600."
          ls -l "$GOOGLE_CRED_PATH"

      - name: Run script
        run: |
          python -V
          python PANEL_INCENDIOS.py
